export enum DomainExceptionCode {
  //common
  NOT_FOUND = 'NOT_FOUND',
  BAD_REQUEST = 'BAD_REQUEST',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  FORBIDDEN = 'FORBIDDEN',
  VALIDATION_FAILED = 'VALIDATION_FAILED',

  //auth
  UNAUTHORIZED = 'UNAUTHORIZED',
  NOT_UNIQUE_ERROR = 'NOT_UNIQUE_ERROR',
  EMAIL_NOT_CONFIRMED = 'EMAIL_NOT_CONFIRMED',
  CONFIRMATION_CODE_EXPIRED = 'CONFIRMATION_CODE_EXPIRED',
  RECOVERY_CODE_EXPIRED = 'RECOVERY_CODE_EXPIRED',
}
